"""empty message

Revision ID: b0f914c0b843
Revises: a9f8fa54e238
Create Date: 2021-12-21 17:42:19.062742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f914c0b843'
down_revision = 'a9f8fa54e238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_order', sa.Column('house_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'booking_order', 'house', ['house_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking_order', type_='foreignkey')
    op.drop_column('booking_order', 'house_id')
    # ### end Alembic commands ###
